name: Deploy Knowledge Vault App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install streamlit beautifulsoup4 faiss-cpu numpy pandas plotly pypdf2 pytrends trafilatura torch; fi
        
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: . # The folder the action should deploy.
        clean: true # Automatically remove deleted files from the deployment
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Configure for Streamlit Cloud
      run: |
        mkdir -p .streamlit
        echo "[server]" > .streamlit/config.toml
        echo "headless = true" >> .streamlit/config.toml
        echo "enableCORS = false" >> .streamlit/config.toml
        echo "port = 5000" >> .streamlit/config.toml
